### ISSUE TITLE
something wrong when access /admin

### ISSUE THREAD

**Issue by vongoethe** [lilxyzz/holo-theme#40]
it reports:
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at Di (/admin/react-dom.production.min.js:168:430) at jb (/admin/react-dom.production.min.js:168:138) at Di (/admin/react-dom.production.min.js:170:84) at jb (/admin/react-dom.production.min.js:168:138) at Di (/admin/react-dom.production.min.js:169:397) at Aa (/admin/react-dom.production.min.js:171:234) at Fi (/admin/react-dom.production.min.js:172:129) at Aa (/admin/react-dom.production.min.js:171:382) at Fi (/admin/react-dom.production.min.js:177:396) at Aa (/admin/react-dom.production.min.js:171:382)

**Comment by lilxyzz** [comment]
Hi @vongoethe this issue should now be resolved. I'm not sure why the gatsby-plugin-netlify-cms was needed, as I understood it had been deprecated. Just a heads up, I have a lot on my plate right now, but I'll do my best to keep things running smoothly here. Cheers
