### ISSUE TITLE
Could not resolve react dependancy when attempting npm install (seems to be CMS specific?)

### ISSUE THREAD

**Issue by grifshot** [lilxyzz/holo-theme#52]
I am **very** new to any level of coding beyond a social media 1.0 WISIWYG editor, so I don't doubt that this is more easily solvable than it seems to me, but I'm having a hard time parsing the specifics of how to resolve this. I have just cloned my branch of the theme to my local machine, moved to the new folder, and attempted `npm install`. This is what is being returned:

![image](https://github.com/user-attachments/assets/5430e3a9-3c0a-469e-b596-9a2c67c0b756)

I am also trying to achieve the Netflity Identity set up detailed in [this tutorial](https://www.netlify.com/blog/2020/07/13/manage-subscriptions-and-protect-content-with-stripe/), so I initially bypassed resolving the `npm install` to run `ntl link` (successful) and `ntl dev` (unsuccessful), and then in error chasing went through `npm install -g gatsby-cli` (successful), and `yarn global add gatsby-cli` (successful); attempts at running `ntl dev` remain unsucsessful, I think because of the npm install issue, and `npm install` attempts continue to give the error above. The error is also returned when I attempt a 'manual' Decap install detailed [here](https://decapcms.org/docs/gatsby/). For reference, here is the `ntl dev` error:

![image](https://github.com/user-attachments/assets/9ecc552c-fd01-468f-b6f5-127ab250a5b6)

I think I have maybe just not installed something that I should have, but I don't have the knowledge to know what, so I'd appreciate any insight into parsing this for something Google-able in a useful way.

[Since this does seem to be CMS specific, for what it's worth my intended CMS data is in a REST API-accessible database and I will need to be using that API in some form; I was going to work out when I got to that point if this requires Decap CMS being 'swapped out' or not, but if it would then I'm equally in want for any guidance on how I remove Decap entirely at this stage instead]

**Comment by lilxyzz** [comment]
Hi, @grifshot I've pushed an update that may resolve the issue you're experiencing. Could you please check it and let me know if it works? Just a heads up, I have a lot on my plate right now, but I'll do my best to keep things running smoothly here. Cheers
